### ISSUE TITLE
データの送信率を設定できるようにする

### ISSUE THREAD

**Issue by hrix** [y-ken/fluent-plugin-gamobile#11]
現在、1,000万ヒット/月の制限に引っかかってしまう場合があるので、1～100%で送信率を設定できるようにしたい

https://support.google.com/analytics/answer/1070983?hl=ja

**Comment by hrix** [comment]
https://github.com/tagomoris/fluent-plugin-sampling-filter
これと組み合わせればいいか

**Comment by hrix** [comment]
fluent-plugin-sampling-filterで間引いてからこのプラグインで受ければOK
http://tagomoris.hatenablog.com/entry/20120223/1329969632

**Comment by y-ken** [comment]
確かにそのような工夫をすると良さそうですね！
