### ISSUE TITLE
送信するコードをユニバーサルアナリィティクス対応にしたい

### ISSUE THREAD

**Issue by hrix** [y-ken/fluent-plugin-gamobile#6]
https://developers.google.com/analytics/devguides/collection/web/?hl=ja
によるとga.jsはレガシーになっている
https://developers.google.com/analytics/devguides/collection/protocol/v1/parameters?hl=ja
にパラメータは書いてある。

**Comment by y-ken** [comment]
引き続きよろしくお願いします。 :+1:

**Comment by hrix** [comment]
Thank you, very much.

**Comment by y-ken** [comment]
#12 の修正でuniversal analytics対応になったという認識でよろしかったでしょうか？

**Comment by hrix** [comment]
universal analyticsのanalytics.js対応になっています。ありがとうございます。別プラグインとしてのニーズは今のところまとまらないので、改めて相談させていただければと思います。
